# Generated by Django 4.2.7 on 2026-01-16 02:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timer', '0008_timer_pause'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('projects', '0001_initial'),
        ('deliverables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_seconds', models.BigIntegerField(default=0, help_text='Total tracked time in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_sessions', models.IntegerField(default=0, help_text='Total completed sessions', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost across all sessions', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_timers', models.IntegerField(default=0, help_text='Total number of timers in workspace', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_customers', models.IntegerField(default=0, help_text='Total number of customers in workspace', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_deliverables', models.IntegerField(default=0, help_text='Total number of deliverables in workspace', validators=[django.core.validators.MinValueValidator(0)])),
                ('active_projects', models.IntegerField(default=0, help_text='Number of active projects', validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_projects', models.IntegerField(default=0, help_text='Number of completed projects', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this aggregate was updated')),
                ('owner', models.ForeignKey(help_text='Workspace owner (one aggregate per workspace)', on_delete=django.db.models.deletion.CASCADE, related_name='workspace_aggregate', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'analytics_workspaceaggregate',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['owner'], name='analytics_w_owner_i_6b8c3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_seconds', models.BigIntegerField(default=0, help_text='Total time tracked by this user (seconds)', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost for this user', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('session_count', models.IntegerField(default=0, help_text='Number of sessions created by this user', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this aggregate was updated')),
                ('user', models.ForeignKey(help_text='The user (team member) this aggregate represents', on_delete=django.db.models.deletion.CASCADE, related_name='user_aggregates', to=settings.AUTH_USER_MODEL)),
                ('workspace_owner', models.ForeignKey(help_text='Workspace owner', on_delete=django.db.models.deletion.CASCADE, related_name='team_member_aggregates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_useraggregate',
                'ordering': ['-total_time_seconds'],
                'indexes': [models.Index(fields=['workspace_owner', 'total_time_seconds'], name='analytics_u_workspa_f15db5_idx'), models.Index(fields=['user'], name='analytics_u_user_id_752fe5_idx')],
                'unique_together': {('user', 'workspace_owner')},
            },
        ),
        migrations.CreateModel(
            name='TimerAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_seconds', models.BigIntegerField(default=0, help_text='Total time tracked for this timer (seconds)', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost for this timer', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('session_count', models.IntegerField(default=0, help_text='Number of sessions for this timer', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this aggregate was updated')),
                ('timer', models.ForeignKey(help_text='The timer this aggregate represents', on_delete=django.db.models.deletion.CASCADE, related_name='timer_aggregate', to='timer.timer')),
                ('workspace_owner', models.ForeignKey(help_text='Workspace owner', on_delete=django.db.models.deletion.CASCADE, related_name='timer_aggregates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_timeraggregate',
                'ordering': ['-total_time_seconds'],
                'indexes': [models.Index(fields=['workspace_owner', 'total_time_seconds'], name='analytics_t_workspa_c58b7b_idx'), models.Index(fields=['timer'], name='analytics_t_timer_i_aed739_idx')],
                'unique_together': {('timer', 'workspace_owner')},
            },
        ),
        migrations.CreateModel(
            name='ProjectAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_seconds', models.BigIntegerField(default=0, help_text='Total time tracked for this project (seconds)', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost for this project', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('session_count', models.IntegerField(default=0, help_text='Number of sessions for this project', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this aggregate was updated')),
                ('project', models.ForeignKey(help_text='The project this aggregate represents', on_delete=django.db.models.deletion.CASCADE, related_name='project_aggregate', to='projects.project', unique=True)),
            ],
            options={
                'db_table': 'analytics_projectaggregate',
                'ordering': ['-total_time_seconds'],
                'indexes': [models.Index(fields=['project'], name='analytics_p_project_4055a8_idx'), models.Index(fields=['total_time_seconds'], name='analytics_p_total_t_1b11bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliverableAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_seconds', models.BigIntegerField(default=0, help_text='Total time tracked for this deliverable (seconds)', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost for this deliverable', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('session_count', models.IntegerField(default=0, help_text='Number of sessions for this deliverable', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this aggregate was updated')),
                ('deliverable', models.ForeignKey(help_text='The deliverable this aggregate represents', on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_aggregate', to='deliverables.deliverable', unique=True)),
            ],
            options={
                'db_table': 'analytics_deliverableaggregate',
                'ordering': ['-total_time_seconds'],
                'indexes': [models.Index(fields=['deliverable'], name='analytics_d_deliver_4168ea_idx'), models.Index(fields=['total_time_seconds'], name='analytics_d_total_t_cf7599_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Aggregation date')),
                ('total_time_seconds', models.BigIntegerField(default=0, help_text='Total time tracked on this date (seconds)', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost on this date', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('session_count', models.IntegerField(default=0, help_text='Number of sessions on this date', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this aggregate was updated')),
                ('workspace_owner', models.ForeignKey(help_text='Workspace owner', on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_dailyaggregate',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['workspace_owner', 'date'], name='analytics_d_workspa_5f5a01_idx'), models.Index(fields=['date'], name='analytics_d_date_140e9e_idx')],
                'unique_together': {('workspace_owner', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CustomerAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_seconds', models.BigIntegerField(default=0, help_text='Total time tracked for this customer (seconds)', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost for this customer', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('session_count', models.IntegerField(default=0, help_text='Number of sessions for this customer', validators=[django.core.validators.MinValueValidator(0)])),
                ('project_count', models.IntegerField(default=0, help_text='Number of projects for this customer', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this aggregate was updated')),
                ('customer', models.ForeignKey(help_text='The customer this aggregate represents', on_delete=django.db.models.deletion.CASCADE, related_name='customer_aggregate', to='customers.customer', unique=True)),
            ],
            options={
                'db_table': 'analytics_customeraggregate',
                'ordering': ['-total_time_seconds'],
                'indexes': [models.Index(fields=['customer'], name='analytics_c_custome_f18aa6_idx'), models.Index(fields=['total_time_seconds'], name='analytics_c_total_t_483754_idx')],
            },
        ),
    ]
