# Generated by Django 4.2.7 on 2026-01-16 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('customers', '0001_initial'),
        ('deliverables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraggregate',
            name='customer',
            field=models.OneToOneField(help_text='The customer this aggregate represents', on_delete=django.db.models.deletion.CASCADE, related_name='customer_aggregate', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='deliverableaggregate',
            name='deliverable',
            field=models.OneToOneField(help_text='The deliverable this aggregate represents', on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_aggregate', to='deliverables.deliverable'),
        ),
        migrations.AlterField(
            model_name='projectaggregate',
            name='project',
            field=models.OneToOneField(help_text='The project this aggregate represents', on_delete=django.db.models.deletion.CASCADE, related_name='project_aggregate', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='workspaceaggregate',
            name='owner',
            field=models.OneToOneField(help_text='Workspace owner (one aggregate per workspace)', on_delete=django.db.models.deletion.CASCADE, related_name='workspace_aggregate', to=settings.AUTH_USER_MODEL),
        ),
    ]
