# Generated by Django 4.2.7 on 2025-12-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='header_color',
            field=models.CharField(default='#3498db', help_text='Hex color code for timer card header', max_length=7),
        ),
    ]
