# Generated by Django 4.2.7 on 2025-12-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0001_initial'),
        ('timer', '0006_customcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='timersession',
            name='deliverable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='deliverables.deliverable'),
        ),
    ]
