# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0007_timersession_deliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timersession',
            name='pause_start_time',
            field=models.DateTimeField(blank=True, help_text='Time when timer was paused (active pause, not resumed yet)', null=True),
        ),
        migrations.CreateModel(
            name='TimerPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause_start_time', models.DateTimeField()),
                ('pause_end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='timer.timersession')),
            ],
            options={
                'db_table': 'timer_app_timerpause',
                'ordering': ['pause_start_time'],
            },
        ),
    ]
